### PR TITLE
feat(upgrade): updated all dependencies

### PR DESCRIPTION
**Pull request by anymaniax**
**What are you adding/fixing?**
Support for angular 6 & rxjs 6

**Have you added tests for your changes?**
No

**Will this need documentation changes?**
No

**Does this introduce a breaking change?**
No

**Other information**
There are some warnings when you start the example app for the bundle size and system.import() into @angular/core

### CODE REVIEW

**Comment by craigsmitham** [comment]
Would love to see this supported for Angular 6

File: example/app/stock-inventory/containers/stock-inventory/stock-inventory.component.ts [hunk 1]
```diff
@@ -3,9 +3,8 @@ import { FormBuilder, FormGroup, FormArray, Validators, AbstractControl } from '
 
 import { StockValidators } from './stock-inventory.validators';
 
-import { Observable } from 'rxjs/Observable';
-import 'rxjs/add/observable/forkJoin';
-import 'rxjs/add/operator/map';
+import { Observable , forkJoin } from 'rxjs';
```
Comment (mgol) [inline example/app/stock-inventory/containers/stock-inventory/stock-inventory.component.ts]: There should be no space before the comma.

File: src/ngxerror.directive.ts [hunk 2]
```diff
@@ -1,12 +1,10 @@
 import { Directive, Input, OnInit, OnDestroy, DoCheck, Inject, HostBinding, forwardRef } from '@angular/core';
 
-import { Observable } from 'rxjs/Observable';
-import { Subject } from 'rxjs/Subject';
-import { Subscription } from 'rxjs/Subscription';
-import 'rxjs/add/operator/filter';
-import 'rxjs/add/operator/map';
-import 'rxjs/add/operator/distinctUntilChanged';
-import 'rxjs/add/observable/combineLatest';
+import { Observable ,  Subject ,  Subscription, combineLatest } from 'rxjs';
```
Comment (mgol) [inline src/ngxerror.directive.ts]: The same remark. Code style is not correct in multiple fixed places.

File: src/ngxerror.directive.ts [hunk 3]
```diff
@@ -1,12 +1,10 @@
 import { Directive, Input, OnInit, OnDestroy, DoCheck, Inject, HostBinding, forwardRef } from '@angular/core';
 
-import { Observable } from 'rxjs/Observable';
-import { Subject } from 'rxjs/Subject';
-import { Subscription } from 'rxjs/Subscription';
-import 'rxjs/add/operator/filter';
-import 'rxjs/add/operator/map';
-import 'rxjs/add/operator/distinctUntilChanged';
-import 'rxjs/add/observable/combineLatest';
+import { Observable,  Subject,  Subscription, combineLatest } from 'rxjs';
```
Comment (mgol) [inline src/ngxerror.directive.ts]: There are still spacing issues here (double spaces after commas).

**Review by mgol — APPROVED** [review]
Looks good to me with two exceptions:
1. I haven't reviewed changes in `webpack.config.js`.
2. Before merging changes in `circle.yml` will need to be reverted.

**Review by paullinney — APPROVED** [review]
Example tested and working ok.
Also packaged and tested against upgraded project.

Anything else required to get this merged in?

**Comment by danieldiazastudillo** [comment]
Come on guys, just one review and we are ok. News about this?

**Comment by jculverwell** [comment]
Would love v6 support soon :)

**Comment by anymaniax** [comment]
Well, until the PR get approved I published my forked version

https://www.npmjs.com/package/@hackages/ngxerrors

**Comment by tamasfoldi** [comment]
What blocks this? @mgol @paullinney @toddmotto Is there any reason or we just have to wait?

**Comment by mgol** [comment]
@tamasfoldi I'm not a maintainer of this module so I can't do anything.

**Review by tamasfoldi — APPROVED** [review]

**Comment by createbuildship** [comment]
guys, review?

**Comment by createbuildship** [comment]
@toddmotto could you have a minute to look into it?

**Comment by Londeren** [comment]
Pleeease 🙏🏻

**Comment by DmitryEfimenko** [comment]
so is this dead?

**Comment by dicbrus** [comment]
Silence here, no any movement? 
@anymaniax forked works fine, thanks

**Comment by dicbrus** [comment]
Silence, why not to merge?

**Review by dicbrus — APPROVED** [review]

**Review by Silentscripter — APPROVED** [review]

**Comment by gracegrimwood** [comment]
Paging @toddmotto! Is this package dead, or...?

**Review by eweap — APPROVED** [review]

**Comment by alignsoft** [comment]
Does this fork include/resolve the `change subject.unsubscribe() to subject.complete()` fix in #32?

**Comment by anymaniax** [comment]
Yes, I did it

**Comment by segux** [comment]
Some fresh news about angular and rxjs 6 support?

**Comment by egandro** [comment]
How can I help? I am getting a "TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_1__.Observable.combineLatest is not a function"

**Comment by segux** [comment]
> How can I help? I am getting a "TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_1__.Observable.combineLatest is not a function"
I Just installed and used Hackages package, he updated with latest rxjs@6 and angular@6

This problem is because api of rxjs on version 6 is broken with 5.

**Comment by egandro** [comment]
Yeah :) I just wanted to fix this issue - but I noticed that ngx-errors is more broken than I thought :( I can't compile on windows. ... no cp / no mkdir -p ... somebody should really fix this. Back here in a few days - i might go with a @hack-hackages/ngx-errors :)

**Comment by egandro** [comment]
The ultimateangular.com guys didn't answer my facebook post. Any success with mail or orther channels? @anymaniax can we fix this?

**Comment by DmitryEfimenko** [comment]
I tried twitter without success.

**Comment by anymaniax** [comment]
@egandro maybe this can help you https://stackoverflow.com/questions/35980322/cant-find-combinelatest-in-rxjs-5-0. The problem I think is that you have two combineLatest (operator and function) and you don't use the good import for that.

**Comment by danieldiazastudillo** [comment]
@anymaniax i'll migrate to your fork, when updating Angular to 6.1.x and beyond this thing breaks like a stick. Besides it's the only package requiring rxjs-compat so i'm leaving to your repo man. All issues, requests, and stuff will be posted over there... be prepared hahaha. I'll help in anything that i can. Greetings.

**Comment by egandro** [comment]
@anymaniax 

> @egandro maybe this can help you https://stackoverflow.com/questions/35980322/cant-find-combinelatest-in-rxjs-5-0. The problem I think is that you have two combineLatest (operator and function) and you don't use the good import for that.

I think this must be fixed in the ngx source. I will do that tomorrow - forking from your branch and you create a @hackages :)

**Comment by arangates** [comment]
bump

**Comment by egandro** [comment]
I give up here. I just copied the 3 files in my project and remove ngx-erros from the dependency list.

Thx for your help! Maybe somebody will fix this project some day...

**Review by ZbignevS — APPROVED** [review]

**Review by ZbignevS — APPROVED** [review]

**Review by Mangor — APPROVED** [review]
